aliyun/openapi-sdk-php

README-CN.md, README.md
Introducing the client's usage request for products that are not supported.
=> Supplementary document

README-CN.md, README.md, tests/Feature/AlimtTest.php
1. Increase the DingTalk QR code.
2. Align the demo code.
3. Add Feature test for Alimt.
=> support dingtalk

src/NlsCloudMeta/NlsCloudMeta.php, src/NlsCloudMeta/NlsCloudMetaVersion.php, src/NlsCloudMeta/V20180518/CreateToken.php, src/NlsCloudMeta/V20180518/NlsCloudMeta.php, src/NlsCloudMeta/V20180518/NlsCloudMetaApiResolver.php, src/ServiceResolverTrait.php, tests/Feature/NlsTest.php
1. Add NLS Cloud Meta Class.
2. Add NLS Cloud Meta Feature Test.
=> support NLS Cloud Meta

.gitignore, .scrutinizer.yml, .travis.yml, CHANGELOG.md, README-CN.md, README.md, appveyor.yml, build/serviceResolverDump.php, codecov.yml, composer.json, composer.lock, phpunit.xml, src/Constants.php, tests/Feature/NlpTest.php
=> Test for Windows

README-CN.md, README.md, tests/Feature/DdsTest.php, tests/Feature/EcsTest.php, tests/Feature/RdsTest.php
- Support Region environment variable.
- Add Region List link to README.md.
=> Support Region environment variable

.scrutinizer.yml, .travis.yml, appveyor.yml
=> Format YML

README-CN.md, README.md, composer.json, src/Dybaseapi/MNS/Constants.php, src/Dybaseapi/MNS/HttpHelper.php, src/Dybaseapi/MNS/MnsClient.php, src/Dybaseapi/MNS/Requests/BaseRequest.php, src/Dybaseapi/MNS/Requests/BatchDeleteMessage.php, src/Dybaseapi/MNS/Requests/BatchReceiveMessage.php, src/Dybaseapi/MNS/Signature.php, tests/Feature/DyBaseApiMnsTest.php, tests/bootstrap.php
- Update readme.
- Update bootstrap for test.
- Support MNS with Feature test.
=> update readme and bootstrap for test

README-CN.md, README.md, composer.json, demo/alimt.php, demo/dysmsapi.php, demo/nlp.php, demo/nlsCloudMeta.php, demo/nlsFiletrans.php, tests/Feature/NlsFiletransTest.php, tests/bootstrap.php
- Support demo.
- Change import env variables method.
=> support demo

composer.json, demo/dysmsapi.php, tests/bootstrap.php
=> support env

CHANGELOG.md
=> support image search

CHANGELOG.md, composer.json, src/ApiResolverTrait.php, src/Constants.php, src/Release.php, src/VersionResolverTrait.php, tests/Feature/DyBaseApiMnsTest.php, tests/Feature/ImageSearchTest.php
- Support release tool.
- Improve test.
=> Support release tool

CHANGELOG.md, src/Release.php
=> Release V1.0.7

tests/bootstrap.php
=> Import env for windows.

CHANGELOG.md, src/Constants.php, src/Release.php
=> release 1.1

.travis.yml
=> improve test

README-CN.md, README.md, docs/1-Installation-CN.md, docs/1-Installation-EN.md
=> Class Map Generation

CHANGELOG.md, src/Constants.php, src/Release.php
=> Remove SVG

CHANGELOG.md, src/Release.php
=> Release 1.2.6

CHANGELOG.md, src/ApiResolverTrait.php, src/Release.php, src/VersionResolverTrait.php, tests/Feature/AegisTest.php, tests/Feature/AlimtTest.php, tests/Feature/CCCTest.php, tests/Feature/CdnTest.php, tests/Feature/CloudApiTest.php, tests/Feature/CsTest.php, tests/Feature/DbsTest.php, tests/Feature/DdsTest.php, tests/Feature/EcsTest.php, tests/Feature/ImageSearchTest.php, tests/Feature/IotTest.php, tests/Unit/ApiResolverTraitTest.php
=> updated tests

demo/green.php, tests/Feature/DbsTest.php, tests/Feature/GreenImageTest.php, tests/Feature/GreenOCRTest.php, tests/Feature/GreenTextTest.php, tests/Feature/GreenVideoTest.php, tests/Feature/GreenVoiceTest.php
=> support tests for green

CHANGELOG.md, composer.json, src/Release.php
=> updated composer.json

CHANGELOG.md, src/Release.php
=> Remove `finmall`

CHANGELOG.md, src/Dbs/V20190306/Api.php, src/Release.php
=> Added Apis for `Dbs`

CHANGELOG.md, src/Release.php
- Supported `Sas`, `Ivision`.
- Added tests for `Sas`, `Ivision`.
=> Release V1.5.1

CHANGELOG.md, README-CN.md, README.md, composer.json, docs/1-Installation-CN.md, docs/1-Installation-EN.md, src/Release.php
=> Release 1.6.0

CHANGELOG.md, src/Release.php
=> release 1.6.1

tests/Feature/AegisTest.php, tests/Feature/AlimtTest.php, tests/Feature/CCCTest.php, tests/Feature/CdnTest.php, tests/Feature/ImageSearchV20180120Test.php, tests/Feature/ImageSearchV20190325Test.php, tests/Feature/RamTest.php, tests/Feature/StsTest.php, tests/Feature/VodClassTest.php, tests/Feature/VodManageTest.php, tests/Feature/VodPlayTest.php, tests/Feature/VodUploadTest.php
=> added tests

src/Alidns/V20150109/AlidnsApiResolver.php, src/CloudAPI/V20160714/CloudAPIApiResolver.php, src/Cloudesl/V20180801/CloudeslApiResolver.php, src/Dbs/V20190306/DbsApiResolver.php, src/Rds/V20140815/RdsApiResolver.php, src/Vod/V20170321/VodApiResolver.php
=> Updated APIs

CHANGELOG.md, src/Release.php
=> Release 1.6.3

README-CN.md, README.md, docs/en/0-Prerequisites.md, docs/en/1-Installation.md, docs/zh/0-Prerequisites.md, docs/zh/1-Installation.md
=> improve docs

CHANGELOG.md, src/Release.php
=> release 1.6.4

CHANGELOG.md, src/Release.php
=> release 1.7.0

README-EN.md, README.md
=> improve readme

tests/Feature/AirecTest.php
=> improved tests

README-zh-CN.md, README.md, docs/en-US/0-Prerequisites.md, docs/en-US/1-Installation.md, docs/zh-CN/0-Prerequisites.md, docs/zh-CN/1-Installation.md
=> updated docs

docs/en-US/1-Installation.md, docs/zh-CN/1-Installation.md
=> Updated documentation for split SDK

README-zh-CN.md, README.md
=> Added troubleshoot link

README-zh-CN.md
=> Update OpenAPI explorer link

README-zh-CN.md, README.md, docs/en-US/0-Prerequisites.md, docs/en-US/1-Installation.md, docs/zh-CN/0-Prerequisites.md, docs/zh-CN/1-Installation.md
delete "switch the Composer mirror" intro
=> doc: format md files

docs/en-US/1-Installation.md, docs/zh-CN/1-Installation.md
=> docs: update README
